version: '3.9'

services:
    client:
        build:
            context: ./client/
        image: client
        restart: always
        env_file:
            - ./.env
        ports:
            - '8088:80'
        depends_on:
            - server

    server:
        build:
            context: ./server/
        image: server
        restart: always
        env_file:
            - ./.env
        ports:
            - '8082:4465'
            - '8083:5000'
        networks:
            - rsn
        depends_on:
            - mongosetup

    mongo1:
        hostname: mongo1
        container_name: localmongo1
        image: mongo
        ports:
            - 8090:27017
        restart: always
        networks:
            - rsn
        entrypoint:
            [
                '/usr/bin/mongod',
                '--bind_ip_all',
                '--replSet',
                'rs0'
            ]

    mongosetup:
        image: mongo
        depends_on:
            - mongo1
        volumes:
            - ./scripts:/scripts
        restart: 'no'
        networks:
            - rsn
        entrypoint: [ 'bash', '/scripts/mongo_setup.sh' ]

networks:
    rsn:
        driver: bridge
