version: '3.9'

services:
  client:
    build:
      context: ./client/
      args:
        - CLIENT_ID=${CLIENT_ID}
        - SECRET_KEY=${SECRET_KEY}
        - REDIRECT_URI=${REDIRECT_URI}
        - SERVER_URI=${SERVER_URI}
        - SOCKET_URI=${SOCKET_URI}
        - MONGO_USERNAME=${MONGO_USERNAME}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - MONGO_CONNECT_URI=${MONGO_CONNECT_URI}
        - MONGO_PORT=${MONGO_PORT}
        - SERVER_PORT=${SERVER_PORT}
        - TOKEN_SECRET=${TOKEN_SECRET}
        - BOT_ACCOUNT=${BOT_ACCOUNT}
        - REFRESH_TOKEN=${REFRESH_TOKEN}
        - LOGIN=${LOGIN}
    image: client
    restart: always
    ports:
      - '8088:80'
    depends_on:
      - server

  server:
    build:
      context: ./server/
    image: server
    restart: always
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - SECRET_KEY=${SECRET_KEY}
      - REDIRECT_URI=${REDIRECT_URI}
      - SERVER_URI=${SERVER_URI}
      - SOCKET_URI=${SOCKET_URI}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_CONNECT_URI=${MONGO_CONNECT_URI}
      - MONGO_PORT=${MONGO_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - BOT_ACCOUNT=${BOT_ACCOUNT}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - LOGIN=${LOGIN}
    ports:
      - '8082:4465'
      - '8083:5000'
    networks:
      - rsn
    depends_on:
      - mongosetup

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    ports:
      - 8090:27017
    restart: always
    networks:
      - rsn
    entrypoint:
      - '/usr/bin/mongod'
      - '--bind_ip_all'
      - '--replSet'
      - 'rs0'

  mongosetup:
    image: mongo
    depends_on:
      - mongo1
    volumes:
      - ./scripts:/scripts
    restart: 'no'
    networks:
      - rsn
    entrypoint: [ 'bash', '/scripts/mongo_setup.sh' ]

networks:
  rsn:
    driver: bridge
